version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: notix-backend
    restart: always
    depends_on:
      - mysql
    environment:
      - ConnectionStrings__NotixDBConnection=server=${DATABASE_HOST};port=3306;user=${DATABASE_USER};password=${DATABASE_PASSWORD};database=${DATABASE_NAME}
    ports:
      - "${BACKEND_PORT}:8080"

  frontend:
    build: ./frontend
    container_name: notix-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - PORT=80  # Serve needs this
    ports:
      - "${FRONTEND_PORT}:80"

volumes:
  mysql_data:
